spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_manager_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

security:
  jwt:
    secret: Y2hvb25hLWxvb25hLW1vb25hLXNvb25hLXRvb25hLXdvb25hLWNhcmQ=
    expiration: 3600000 # 1 hour
